### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by dartiss** [therepm/there-desktop#14]
There uses a high amount of CPU - 11%+ on my 2017 MBP right now. I also have two There Helpers running too - one at 8% CPU and the other at 5% (so, a total, across all instances of 25% CPU!). For this reason I've had to temporarily disable There.

**Comment by morajabi** [comment]
I'm optimizing it since yesterday (but actually a bit busy on weekend) so I cut the app size by ~ 90 MB, reduced Energy Impact and I'm debugging CPU usage, it'd drop to ~0-3% while inactive after the optimization.
