### ISSUE TITLE
[Suggestion] Image/Static map for places

### ISSUE THREAD

**Issue by harrisrobin** [therepm/there-desktop#15]
Hey!

So I'm noticing that the places circle is empty for me. Unless this is a bug, i recommend using a static google map of the location.

<img width="344" alt="screenshot 2018-04-18 14 19 21" src="https://user-images.githubusercontent.com/3880008/38950620-10e9ecc8-4314-11e8-8bdc-79bee4919847.png">

Cheers!

**Comment by morajabi** [comment]
<img width="194" alt="screen shot 2018-05-29 at 7 42 16 pm" src="https://user-images.githubusercontent.com/12202757/40668156-07e1a456-6379-11e8-896e-d95337ded57e.png">

What do you think about this @harrisrobin? Would like to know how does it look to your eyes? :)

**Comment by harrisrobin** [comment]
@morajabi looks good but I would apply some filter/gradient over those icons to make them flush a bit more. I feel that the flags and user avatars can really clash. What do you think?

**Comment by morajabi** [comment]
I agree, I was going to add some gradient 🙂

**Comment by morajabi** [comment]
It being released today!
